"use client";
import { useActionState, useMemo, useState } from "react";
import { BotOff, Download, Send, ShieldAlert } from "lucide-react";
import { AppShell } from "@/components/shell";
import { Status } from "@/components/status";
import { resetFailedSendAction, saveReviewAction, sendReviewAction, type ActionState } from "@/app/actions";
import { calculateReviewDecision, type ReviewDecision, type RubricLevel } from "@/domain/workflow";
import type { ReviewRow } from "@/server/data";

const labels:Record<RubricLevel,string>={weak:"ضعيف",acceptable:"مقبول",strong:"قوي",unassessed:"غير قابل للتقييم"};
const decisionLabels:Record<ReviewDecision,string>={approved:"معتمد",approved_with_changes:"معتمد بتعديلات",resubmit:"إعادة تقديم"};
const initial:ActionState={};
export default function ReviewEditor({review,user,smtpReady}:{review:ReviewRow;user:{name:string;role:string};smtpReady:boolean}){
 const initialDecision:ReviewDecision=(review.lead_decision||review.calculated_decision)==="approved"&&review.criteria.some(c=>c.blocking&&c.level==="unassessed")?"approved_with_changes":(review.lead_decision||review.calculated_decision);
 const [criteria,setCriteria]=useState(review.criteria); const [decision,setDecision]=useState<ReviewDecision>(initialDecision); const [reason,setReason]=useState(review.lead_reason||""); const [confirmed,setConfirmed]=useState(false);
 const [saveState,saveAction,saving]=useActionState(saveReviewAction,initial); const [sendState,sendAction,sending]=useActionState(sendReviewAction,initial);
 const calculated=useMemo(()=>calculateReviewDecision(criteria),[criteria]); const override=decision!==calculated.decision;
 const update=(id:number,patch:Partial<{level:RubricLevel;quote:string;fix:string}>)=>setCriteria(items=>items.map(x=>x.id===id?{...x,...patch}:x));
  const finalLocked=["sending","sent","send_failed"].includes(review.status); const fullApprovalAllowed=!criteria.some(c=>c.blocking&&c.level==="unassessed");
 return <AppShell area="committee" title="مراجعة المقترح" userName={user.name}><div className="page">
  <div className="demo-banner"><ShieldAlert size={17}/> هذه مراجعة تشغيلية. لا يوجد تقييم آلي؛ أدخل الدرجات والاقتباسات يدوياً.</div>
  <div className="page-head"><div><h2>{review.project_name}</h2><p><span className="project-code">{review.public_id}</span> · {review.owner_name}</p></div><Status tone={review.status==="sent"?"green":review.status==="send_failed"?"red":"amber"}>{review.status==="sent"?"أُرسل":review.status==="send_failed"?"فشل الإرسال":"مسودة"}</Status></div>
  <div className="notice notice-warning"><BotOff size={19}/><div><strong>المعيار السادس معطّل.</strong> لا تدخله المنصة في اعتماد كامل حتى تصل الأرقام المركزية.</div></div>
  <section className="card proposal-source"><div className="card-header"><h3>مصدر المقترح</h3>{review.original_name&&<a className="button button-secondary" href={`/api/proposals/${review.proposal_id}/download`}><Download size={15}/> تنزيل {review.original_name}</a>}</div>{review.pasted_text&&<div className="card-body proposal-text">{review.pasted_text}</div>}{review.notes&&<div className="card-body"><strong>ملاحظات الفريق:</strong> {review.notes}</div>}</section>
  <div className="grid-2 review-layout"><section className="rubric-list">{criteria.map(c=><article className="rubric-item" key={c.id}><div className="rubric-top"><div><div className="rubric-title"><h4>{c.id}. {c.title} {c.blocking&&"⛔"}</h4><span className="weight">الوزن {c.weight}</span></div><div className="field"><label>الاقتباس الحرفي</label><textarea disabled={c.id===6||finalLocked} onChange={e=>update(c.id,{quote:e.target.value})} value={c.quote}/></div><div className="field"><label>الإصلاح المطلوب</label><textarea disabled={c.id===6||finalLocked} onChange={e=>update(c.id,{fix:e.target.value})} value={c.fix}/></div></div><div className="field"><label>النتيجة</label><select disabled={c.id===6||finalLocked} value={c.level} onChange={e=>update(c.id,{level:e.target.value as RubricLevel})}>{Object.entries(labels).filter(([level])=>!c.checklist||level!=="acceptable").map(([level,label])=><option key={level} value={level}>{label}</option>)}</select></div></div></article>)}</section>
   <aside className="card review-summary"><div className="card-header"><h3>القرار النهائي</h3></div><div className="card-body"><span>المجموع الحالي</span><div className="score">{calculated.total}<small> / 38</small></div><p>المحسوب: <strong>{decisionLabels[calculated.decision]}</strong></p><div className="divider"/>
    <form action={saveAction}><input name="proposalId" type="hidden" value={review.proposal_id}/><input name="criteriaJson" type="hidden" value={JSON.stringify(criteria)}/><button className="button button-secondary" disabled={saving||finalLocked} style={{width:"100%"}}>{saving?"جارٍ الحفظ…":"حفظ المراجعة"}</button>{saveState.error&&<p className="field-error">{saveState.error}</p>}{saveState.success&&<p className="success-text">{saveState.success}</p>}</form>
    <div className="divider"/><form action={sendAction}><input name="proposalId" type="hidden" value={review.proposal_id}/><input name="criteriaJson" type="hidden" value={JSON.stringify(criteria)}/><div className="field"><label htmlFor="leadDecision">قرار القائد</label><select disabled={user.role!=="committee_lead"||finalLocked} id="leadDecision" name="leadDecision" onChange={e=>setDecision(e.target.value as ReviewDecision)} value={decision}>{fullApprovalAllowed&&<option value="approved">معتمد</option>}<option value="approved_with_changes">معتمد بتعديلات</option><option value="resubmit">إعادة تقديم</option></select></div>{!fullApprovalAllowed&&<p className="field-error">الاعتماد الكامل غير متاح وفيه معيار حاجب معطّل.</p>}<div className="field"><label htmlFor="leadReason">سبب قرار القائد {override&&"(إلزامي)"}</label><textarea disabled={user.role!=="committee_lead"||finalLocked} id="leadReason" name="leadReason" onChange={e=>setReason(e.target.value)} value={reason}/></div><label className="check-row"><input checked={confirmed} disabled={finalLocked} onChange={e=>setConfirmed(e.target.checked)} type="checkbox"/> راجعت النص الذي سيصل للفريق</label>{!smtpReady&&<p className="field-error">الإرسال مقفل حتى تضبط إعدادات SMTP.</p>}<button className="button button-primary" disabled={sending||!confirmed||!smtpReady||user.role!=="committee_lead"||finalLocked||(override&&!reason.trim())} style={{width:"100%"}}><Send size={16}/>{sending?"جارٍ الإرسال…":"اعتماد وإرسال"}</button>{sendState.error&&<p className="field-error">{sendState.error}</p>}{sendState.success&&<p className="success-text">{sendState.success}</p>}</form>
    {user.role==="committee_lead"&&["sending","send_failed"].includes(review.status)&&<><div className="divider"/><form action={resetFailedSendAction}><input name="proposalId" type="hidden" value={review.proposal_id}/><label className="check-row"><input name="confirmNoDelivery" required type="checkbox" value="yes"/> راجعت البريد المرسل وتأكدت أن الرسالة لم تصل</label><button className="button button-danger" style={{width:"100%",marginTop:10}}>إعادة فتح الإرسال يدوياً</button></form></>}
   </div></aside>
  </div>
 </div></AppShell>;
}
